In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#Importing Numpy

import numpy as np

**Numpy Attributes**

Berikut terdapat beberapa contoh penggunaan atribut dari Numpy:

*   *Dimension*, digunakan untuk melihat dimensi yang dimiliki suatu numpy array
*   *Shape*, digunakan untuk mengetahui berapa jumlah baris dan kolom dari suatu numpy array
*   *type*, digunakan untuk mengetahui tipe data yang dimiliki suatu numpy array
*   *itemsize*, untuk mwlihat ukuran memori yang dibutuhkan untuk menyimpan sebuah numpy array
*   *nbytes*, digunakan untuk menghitung total bytes yang dimiliki suatu numpy array.

In [10]:
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])
print(my_numpy)

# dimensi
print('\nDimensi my_numpy: ',my_numpy.ndim)

# shape
print('\nShape my_numpy: ',my_numpy.shape) 

# type
print('\nType my_numpy: ',my_numpy.dtype)

# size
print('\nSize my_numpy: ',my_numpy.itemsize)

# dimensi
print('\nNbyte my_numpy: ',my_numpy.nbytes)

[[1 2 3 4 5]
 [6 7 8 9 0]]

Dimensi my_numpy:  2

Shape my_numpy:  (2, 5)

Type my_numpy:  int64

Size my_numpy:  8

Nbyte my_numpy:  80


In [11]:
'''
Indexing pada array sama dengan list
'''
my_numpy[1][2:]

array([8, 9, 0])

In [12]:
# Slicing Array

# [start : stop :step]
nmp = np.array(range(10))
print(nmp)
nmp[0:6:2] #dimulai dari index 0, hingga index 6, dengan langkah/step 2 index

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4])

In [14]:
# multidimension
print(my_numpy) 
my_numpy[1:,2:]

[[1 2 3 4 5]
 [6 7 8 9 0]]


array([[8, 9, 0]])

In [15]:
# Joining Array
my_numpy = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,0]
                    ])

nmpy = np.array([
                [1,2,3,1,4], 
                [2,3,5,3,5]
                ])

np.concatenate([my_numpy, nmpy])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 1, 4],
       [2, 3, 5, 3, 5]])

**Objek Pandas : Series vs DataFrame**
Series dan Dataframe ini adalah suatu objek tempat kita menyimpan data secara terstruktur. Perbedaan dari Series dan DataFrame ini terletak pada strukturnya dan juga attribute dan method-method yang mereka miliki, untuk perbedaan strukturnya adalah sebagai berikut :

*   Series adalah objek 1 dimensi
*   DataFrame adalah suatu objek 2 dimensi, mirip seperti tabel

***Series***

Series adalah suatu objek satu dimensi yang dapat menyimpan berbagai jenis tipe data seperti integer, string, dan lain sebagainya. tipe data dari objek series ini harus seragam. Jika kita pahami lebih lanjut, series itu seperti gabungan antara list dengan dictionary. Series memiliki persamaan dengan list yaitu dapat dilakukan metode slicing, yaitu mengakses/indexing pada object series tersebut (yang akan dipelajari di hari ke-2). Juga series memiliki persamaan dengan dictionary yaitu index yang dimiliki series berguna seperti keys pada dictionary.

Untuk membuat series berikut contohnya:

In [16]:
import pandas as pd

x = pd.Series([6,3,4,6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64


In [21]:
'''
Series memiliki satu sumbu/index saja, dari contoh di atas sumbu/index tersebut berada satu baris, yaitu 0, 1, 2, 3. 
kita bisa mengubah sumbu/index tersebut dengan sebagai berikut :
'''
# jumlah index harus sama dengan jumlah data.
# cara pertama

x.index = ['a', 'b', 'c', 'd']
print(x)

# cara kedua
x = pd.Series([6,3,4,6], index=['w', 'x', 'y', 'z'])
print(x)

# check tipe data
print(type(x))

a    6
b    3
c    4
d    6
dtype: int64
w    6
x    3
y    4
z    6
dtype: int64
<class 'pandas.core.series.Series'>


**DataFrame**

DataFrame adalah suatu objek 2 dimensi tempat menyimpan data dengan lebih terstruktur. dataframe memiliki 2 index, yaitu index baris dan index columns. Dalam satu column dataframe harus memiliki tipe data yang sama. tapi antar columnnya dataframe bisa memiliki jenis data yang berbeda. untuk lebih jelasnya perhatikan contoh berikut :

In [23]:
import pandas as pd

df = pd.DataFrame({'tipe_int': [50, 21], 'tipe_string': ['a', 'b']})
print(df)
# check tipe data
print(type(df))

   tipe_int tipe_string
0        50           a
1        21           b
<class 'pandas.core.frame.DataFrame'>


**Membaca data dari File** 

Membaca data dari file adalah hal pertama yang dilakukan dalam suatu pekerjaan data science. maka hal ini sangat penting.

Ada beberapa tipe file yang biasa di gunakan untuk menyimpan data, seperti database, excel, csv. disini akan di jelaskan beberapa saja tentang cara membaca file dari berbagai sumber tersebut. akan di jelaskan 2 yaitu csv dan excel karena csv dan excel adalah sumber yang biasa di gunakan untuk menyimpan data karena kemudahannya. ok kita langsung saja.

Pandas menyediakan metode yang berbeda untuk membaca file dengan tipe berbeda. Untuk membaca file bertipe csv, pandas menggunakan suatu metode read_csv(), untuk membaca file bertipe excel pandas menggunakan suatu metode bernama read_excel. perhatikan contoh berikut :

In [31]:
# membaca dari dari csv
df_from_csv = pd.read_csv('/content/drive/My Drive/Bootcamp Data Science Python/Pekan 2/1. Pandas Introduction/Data COVID-19 Jawa Barat.csv')

# membaca data dari excel
df_from_excel = pd.read_excel('/content/drive/My Drive/Bootcamp Data Science Python/Pekan 2/1. Pandas Introduction/Data COVID-19 Jawa Barat.xlsx')

Untuk menggunakan method tersebut kita hanya perlu memasukan argument wajib, yaitu path dari file yang akan kita baca. Kemudian yang perlu diperhatikan adalah, file yang kita baca (csv, excel, dkk) berada pada directory/folder yang sama dengan .ipynb tersebut. Sedangkan pada google colab, silahkan tonton video di bawah ya. Lebih lanjutnya lagi pandas memiliki beberapa argumen optional, kalian bisa mecarinya dengan menggunakan metode help yang telah kalian pelajari sebelumnya

Pemeriksaan sederhana tentang Karakteristik Data 
**bold text**
Pandas memiliki beberapa method untuk memahami gambaran besar karakteristik dari data kita. diantaranya adalah:


*   head()
*   tail()
*   info()
*   describe()

Metode head() secara default adalah untuk melihat 5 pertama data kita, sedangkan metode tail() secara default untuk melihat 5 data kita dari terakhir. kita bisa mengganti jumlah data yang akan di tampilkan dengan memberikan data integer sebagai argument terhadap metode tersebut. contohnya sebagai beriktu:

In [32]:
df_from_csv.head()

tanggal  kode_prov            nama_prov  kode_kab  \
0  2020-08-01         32  Provinsi Jawa Barat         0   
1  2020-08-01         32  Provinsi Jawa Barat      3201   
2  2020-08-01         32  Provinsi Jawa Barat      3202   
3  2020-08-01         32  Provinsi Jawa Barat      3203   
4  2020-08-01         32  Provinsi Jawa Barat      3204   

                nama_kab  closecontact  closecontact_dikarantina  \
0  BELUM TERIDENTIFIKASI             0                         0   
1             KAB. BOGOR             0                         0   
2          KAB. SUKABUMI             0                         0   
3           KAB. CIANJUR             0                         0   
4           KAB. BANDUNG             0                         0   

   closecontact_discarded  suspect  suspect_diisolasi  ...  \
0                       0        0                  0  ...   
1                       0        0                  0  ...   
2                       0        0                  0  ...   
3                       0        0                  0  ...   
4                       0        0                  0  ...   

   pertumbuhan_suspect_discarded  pertumbuhan_suspect_diisolasi  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              0                              0   

   pertumbuhan_probable  pertumbuhan_probable_discarded  \
0                     0                               0   
1                     0                               0   
2                     0                               0   
3                     0                               0   
4                     0                               0   

   pertumbuhan_probable_diisolasi  pertumbuhan_probable_meninggal  \
0                               0                               0   
1                               0                               0   
2                               0                               0   
3                               0                               0   
4                               0                               0   

   pertumbuhan_confirmation  pertumbuhan_confirmation_selesai  \
0                         0                                19   
1                         4                                 0   
2                         0                                 0   
3                         0                                 0   
4                         1                                 0   

   pertumbuhan_confirmation_meninggal  Unnamed: 31  
0                                   0          NaN  
1                                   0          NaN  
2                                   0          NaN  
3                                   0          NaN  
4                                   0          NaN  

[5 rows x 32 columns]

In [33]:
df_from_csv.tail()

tanggal  kode_prov            nama_prov  kode_kab          nama_kab  \
18895  2022-06-06         32  Provinsi Jawa Barat      3275       KOTA BEKASI   
18896  2022-06-06         32  Provinsi Jawa Barat      3276        KOTA DEPOK   
18897  2022-06-06         32  Provinsi Jawa Barat      3277       KOTA CIMAHI   
18898  2022-06-06         32  Provinsi Jawa Barat      3278  KOTA TASIKMALAYA   
18899  2022-06-06         32  Provinsi Jawa Barat      3279       KOTA BANJAR   

       closecontact  closecontact_dikarantina  closecontact_discarded  \
18895         66843                     66721                     122   
18896         74447                     70031                    4416   
18897         15084                     14902                     182   
18898         12812                     12478                     334   
18899          3286                      3221                      65   

       suspect  suspect_diisolasi  ...  pertumbuhan_suspect_discarded  \
18895    23158              22838  ...                              0   
18896    25914              25225  ...                              0   
18897     4517               3947  ...                              0   
18898     2681               2637  ...                              0   
18899     3057               2988  ...                              0   

       pertumbuhan_suspect_diisolasi  pertumbuhan_probable  \
18895                              0                     0   
18896                              0                     0   
18897                              0                     0   
18898                              0                     0   
18899                              0                     0   

       pertumbuhan_probable_discarded  pertumbuhan_probable_diisolasi  \
18895                               0                               0   
18896                               0                               0   
18897                               0                               0   
18898                               0                               0   
18899                               0                               0   

       pertumbuhan_probable_meninggal  pertumbuhan_confirmation  \
18895                               0                         0   
18896                               0                         0   
18897                               0                         0   
18898                               0                         0   
18899                               0                         0   

       pertumbuhan_confirmation_selesai  pertumbuhan_confirmation_meninggal  \
18895                                 0                                   0   
18896                                 0                                   0   
18897                                 0                                   0   
18898                                 0                                   0   
18899                                 0                                   0   

       Unnamed: 31  
18895          NaN  
18896          NaN  
18897          NaN  
18898          NaN  
18899          NaN  

[5 rows x 32 columns]

info() adalah suatu method untuk melakukan summary terhadap data yang memberikan informasi tentang tipe dari index data, tipe dari column data, non-null values pada setiap column dan jumlah memory yang digunakan. berikut adalah contohnya:

In [34]:
df = pd.DataFrame({'tipe_int': [50, 21], 'tipe_string': ['a', 'b']})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   tipe_int     2 non-null      int64 
 1   tipe_string  2 non-null      object
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


describe() adalah sutau metode yang menghasilkan kesimpulan deskriptif statistik dari data. kesimpulan deskriptif statistik yang dihasilkan adalah seperti central tendency, dispersi dan bentuk distributsi dari data. untuk mengetahui lebih dalam tentang deskriptik statistik silahkan baca artikel ini. berikut contoh penggunaan metode ini.

In [35]:
df_from_csv.describe()

kode_prov      kode_kab  closecontact  closecontact_dikarantina  \
count    18900.0  18900.000000  18900.000000              18900.000000   
mean        32.0   3115.928571  13859.346984              13381.933280   
std          0.0    600.458872  17008.317927              16577.039525   
min         32.0      0.000000      0.000000                  0.000000   
25%         32.0   3206.750000   1902.000000               1902.000000   
50%         32.0   3213.500000   6270.000000               6169.000000   
75%         32.0   3272.250000  20257.000000              17737.250000   
max         32.0   3279.000000  74447.000000              70031.000000   

       closecontact_discarded       suspect  suspect_diisolasi  \
count            18900.000000  18900.000000       18900.000000   
mean               477.413704   6005.632593        5734.593280   
std               1037.353383   6759.216325        6423.063725   
min                  0.000000      0.000000           0.000000   
25%                  0.000000   1494.000000        1453.000000   
50%                 53.500000   3090.000000        2988.000000   
75%                474.000000   8153.250000        7472.000000   
max               5927.000000  27212.000000       25800.000000   

       suspect_discarded      probable  probable_diisolasi  ...  \
count       18900.000000  18900.000000        18900.000000  ...   
mean          162.726402    160.869312           98.287989  ...   
std           502.931171    357.916341          290.798581  ...   
min             0.000000      0.000000            0.000000  ...   
25%             0.000000     14.000000            0.000000  ...   
50%            13.000000     38.000000            3.000000  ...   
75%           104.000000    108.000000           38.000000  ...   
max          3678.000000   1938.000000         1544.000000  ...   

       pertumbuhan_suspect_discarded  pertumbuhan_suspect_diisolasi  \
count                   18900.000000                   18900.000000   
mean                       11.022116                       0.453333   
std                       150.471926                      10.491306   
min                         0.000000                       0.000000   
25%                         0.000000                       0.000000   
50%                         0.000000                       0.000000   
75%                         0.000000                       0.000000   
max                      8233.000000                     653.000000   

       pertumbuhan_probable  pertumbuhan_probable_discarded  \
count          18900.000000                    18900.000000   
mean               0.339153                        0.211587   
std                4.577903                        3.577854   
min                0.000000                        0.000000   
25%                0.000000                        0.000000   
50%                0.000000                        0.000000   
75%                0.000000                        0.000000   
max              295.000000                      268.000000   

       pertumbuhan_probable_diisolasi  pertumbuhan_probable_meninggal  \
count                    18900.000000                    18900.000000   
mean                         0.014603                        0.112963   
std                          0.475661                        2.054367   
min                          0.000000                        0.000000   
25%                          0.000000                        0.000000   
50%                          0.000000                        0.000000   
75%                          0.000000                        0.000000   
max                         34.000000                      163.000000   

       pertumbuhan_confirmation  pertumbuhan_confirmation_selesai  \
count              18900.000000                      18900.000000   
mean                  58.213175                         57.487725   
std                  187.022189                        309.232872   